### ISSUE TITLE
Segfault from psk_demodulator

### ISSUE THREAD

**Issue by gkatev** [surligas/gr-cs330#4]
Hello,
While attempting to run the project flowgraph without any modifications whatsoever I encounter a segmentation fault which appears to originate from the PSK demodulator block. From what I gather, it's due to the indexing of output_items in psk_demodulator_impl::work(), in lib/psk_demodulator_impl.cc:735.

**Comment by surligas** [comment]
Good catch George! 

The line should be not there, as there is no output stream defined. In other words, this is a sink block with only on input. The outputs should be produced however, with the asynchronous API like the description of the project describes. 

I am fixing it asap.

**Comment by surligas** [comment]
Fixed  4dc652e
